#!/bin/bash
# aliases
alias vi="nvim"
alias vim="nvim"
alias reload="source ~/.zshrc"
export EDITOR="nvim"


eval "$(oh-my-posh init zsh)"
eval "$(mise activate zsh)"

[ -s "/Users/james/.scm_breeze/scm_breeze.sh" ] && source "/Users/james/.scm_breeze/scm_breeze.sh"
eval "$(zoxide init zsh)"
