name: "Update Nix"

on:
  pull_request:
  schedule:
    # https://crontab.guru/#0_0_*_*_6
    # Run weekly on saturday's
    - cron: "0 0 * * 6"
jobs:
  installs:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: "main"
      - uses: cachix/install-nix-action@v31.10.5
      - name: Update nix flake
        working-directory: ./dot_config/nix-darwin
        run: nix flake update
      - name: check for update
        working-directory: ./dot_config/nix-darwin
        run: |
          DIFF="$(git diff --name-only)"
          NUM_CHANGES="$(echo $DIFF | wc -l)"

          if [[ "$NUM_CHANGES" -gt 0 ]]; then
            echo "Change(s) $NUM_CHANGES"
            echo TODO MAKE PR w changes
            echo $DIFF
            # Create PR
            TODAY="$(date +"%Y-%m-%d")"
            BRANCH_NAME="bot/nix-update-$TODAY"
            git checkout -b "$BRANCH_NAME"
            git add flake.nix
            git commit -m "chore: update flake.nix $(date +"%Y-%m-%d")"
            git push -u origin $BRANCH_NAME
            gh pr create --title "Chore: Update nix flake ($TODAY)" --body "This is an automated nix flake update. Merge when ready" --reviewer "jbarzegar"
          else
            echo "No changes in flake detected"
          fi
